export const BUSINESS_SEGMENTS = [
  { value: "office", label: "Escritório" },
  { value: "retail", label: "Loja / Varejo" },
  { value: "restaurant", label: "Padaria / Restaurante / Café" },
  { value: "clinic", label: "Clínica / Consultório" },
  { value: "coworking", label: "Coworking" },
  { value: "showroom", label: "Showroom" },
  { value: "hotel", label: "Hotel / Hospedagem" },
  { value: "gym", label: "Academia / Estúdio" },
  { value: "other", label: "Outro" },
] as const

export const BUDGET_RANGES = [
  { value: "0-50k", label: "Até R$ 50.000" },
  { value: "50k-100k", label: "R$ 50.000 - R$ 100.000" },
  { value: "100k-200k", label: "R$ 100.000 - R$ 200.000" },
  { value: "200k-500k", label: "R$ 200.000 - R$ 500.000" },
  { value: "500k-1M", label: "R$ 500.000 - R$ 1.000.000" },
  { value: "1M+", label: "Acima de R$ 1.000.000" },
  { value: "undefined", label: "Ainda não definido" },
] as const

export const BRAZILIAN_STATES = [
  { value: "AC", label: "Acre" },
  { value: "AL", label: "Alagoas" },
  { value: "AP", label: "Amapá" },
  { value: "AM", label: "Amazonas" },
  { value: "BA", label: "Bahia" },
  { value: "CE", label: "Ceará" },
  { value: "DF", label: "Distrito Federal" },
  { value: "ES", label: "Espírito Santo" },
  { value: "GO", label: "Goiás" },
  { value: "MA", label: "Maranhão" },
  { value: "MT", label: "Mato Grosso" },
  { value: "MS", label: "Mato Grosso do Sul" },
  { value: "MG", label: "Minas Gerais" },
  { value: "PA", label: "Pará" },
  { value: "PB", label: "Paraíba" },
  { value: "PR", label: "Paraná" },
  { value: "PE", label: "Pernambuco" },
  { value: "PI", label: "Piauí" },
  { value: "RJ", label: "Rio de Janeiro" },
  { value: "RN", label: "Rio Grande do Norte" },
  { value: "RS", label: "Rio Grande do Sul" },
  { value: "RO", label: "Rondônia" },
  { value: "RR", label: "Roraima" },
  { value: "SC", label: "Santa Catarina" },
  { value: "SP", label: "São Paulo" },
  { value: "SE", label: "Sergipe" },
  { value: "TO", label: "Tocantins" },
] as const